name: MJ Summers
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262626'
    - '#cf0000'
    - '#747474'
    - '#acacac'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
