name: MJ Summers
favicon: null
layout_spectrum: 0.31835
typography_spectrum: 0.14746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a6a6a6'
    - '#212121'
    - '#6f6f6f'
    - '#c23123'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.6619395553134382
purpose: []
